[package]
name = "btfdump"
version = "0.0.1"
authors = ["Andrii Nakryiko <andriin@fb.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
goblin = "0.0.20"
object = "0.11.0"
memmap = "0.7.0"
scroll = "0.9.2"
scroll_derive = "0.9.5"
