[package]
name = "btfdump"
description = "BTF introspection tool"
version = "0.0.2"
authors = ["Andrii Nakryiko <andrii@kernel.org>"]
license = "BSD-2-Clause"
edition = "2018"
readme = "README.md"
repository = "https://github.com/anakryiko/btfdump"
keywords = ["btf", "bpf"]

[lib]
name = "btf"
path = "src/lib.rs"

[[bin]]
name = "btf"
path = "src/main.rs"

[dependencies]
structopt = "0.2"
goblin = "0.0.20"
object = "0.11.0"
memmap = "0.7.0"
scroll = "0.9.2"
scroll_derive = "0.9.5"
regex = "1"
lazy_static = "1"
bitflags = "1"

[dependencies.clap]
version = "2.32"
features = ["wrap_help"]
