[package]
name = "btfdump"
version = "0.0.1"
authors = ["Andrii Nakryiko <andriin@fb.com>"]
edition = "2018"
publish = false

[lib]
name = "btf"
path = "src/lib.rs"

[[bin]]
name = "btf"
path = "src/main.rs"

[dependencies]
structopt = "0.2.10"
goblin = "0.0.20"
object = "0.11.0"
memmap = "0.7.0"
scroll = "0.9.2"
scroll_derive = "0.9.5"
regex = "1"
lazy_static = "1"
