name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [dev, release]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.profile }}

      - run: cargo build  --profile ${{ matrix.profile }} --all-targets
      - run: cargo test   --profile ${{ matrix.profile }} --all-targets
      - run: cargo clippy --profile ${{ matrix.profile }} --all-targets -- --deny warnings
